# Generated by Django 3.1.3 on 2020-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0021_auto_20201119_0932"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeobj",
            old_name="codelist",
            new_name="version",
        ),
        migrations.RenameField(
            model_name="definitionrule",
            old_name="codelist",
            new_name="version",
        ),
        migrations.AlterUniqueTogether(
            name="definitionrule",
            unique_together={("version", "code")},
        ),
    ]
