# Generated by Django 3.1.3 on 2020-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0022_auto_20201119_1434"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefinitionRule",
        ),
    ]
