# Generated by Django 3.1.3 on 2020-11-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0023_delete_definitionrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="codelists.codelistversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("version", "slug")},
            },
        ),
        migrations.AddField(
            model_name="codeobj",
            name="status",
            field=models.CharField(
                choices=[
                    ("+", "Included with descendants"),
                    ("(+)", "Included by ancestor"),
                    ("-", "Excluded with descendants"),
                    ("(-)", "Excluded by ancestor"),
                ],
                default="?",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="codeobj",
            unique_together={("version", "code")},
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="codelists.codeobj",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="codelists.search",
                    ),
                ),
            ],
            options={
                "unique_together": {("search", "code_obj")},
            },
        ),
    ]
