# Generated by Django 3.1.3 on 2020-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0024_auto_20201119_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeobj",
            name="status",
            field=models.CharField(max_length=3),
        ),
        migrations.AddConstraint(
            model_name="codeobj",
            constraint=models.CheckConstraint(
                check=models.Q(status__in=["+", "(+)", "-", "(-)"]),
                name="codelists_codeobj_status_valid",
            ),
        ),
    ]
