# Generated by Django 3.1.3 on 2020-11-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0025_auto_20201119_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelist",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="codelist",
            name="methodology",
            field=models.TextField(null=True),
        ),
    ]
