# Generated by Django 3.1.3 on 2020-11-19 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("builder", "0002_auto_20200929_1649"),
    ]

    operations = [
        migrations.RenameField(
            model_name="code",
            old_name="codelist",
            new_name="draft",
        ),
        migrations.RenameField(
            model_name="search",
            old_name="codelist",
            new_name="draft",
        ),
        migrations.AlterField(
            model_name="draftcodelist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="code",
            unique_together={("draft", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="search",
            unique_together={("draft", "slug")},
        ),
    ]
