# Generated by Django 3.1.3 on 2020-11-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_auto_20201119_1337"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Code",
            new_name="CodeObj",
        ),
        migrations.RenameField(
            model_name="searchresult",
            old_name="code",
            new_name="code_obj",
        ),
        migrations.AlterUniqueTogether(
            name="searchresult",
            unique_together={("search", "code_obj")},
        ),
    ]
