# Generated by Django 3.1.3 on 2020-11-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_auto_20201119_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeobj",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_objs",
                to="builder.draftcodelist",
            ),
        ),
    ]
