# Generated by Django 3.1.3 on 2020-11-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0026_auto_20201119_1621"),
        ("builder", "0006_auto_20201119_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftcodelist",
            name="codelist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="codelists.codelist",
            ),
        ),
    ]
